# Generated by Django 5.1.4 on 2025-01-12 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='軸名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '分類軸',
                'verbose_name_plural': '分類軸',
            },
        ),
        migrations.CreateModel(
            name='MappedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='入力テキスト')),
                ('mapped_data', models.JSONField(default=dict, verbose_name='マッピング結果')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('used_keys', models.JSONField(default=list, verbose_name='使用した軸')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='入力トークン数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='出力トークン数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='合計トークン数')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='概算コスト(USD)')),
            ],
            options={
                'verbose_name': 'マッピングテキスト',
                'verbose_name_plural': 'マッピングテキスト',
            },
        ),
        migrations.CreateModel(
            name='ProcessedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('processed_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
